### PR TITLE
[JENKINS-26941] Update to non-deprecated artifact archiving mechanism

### PR DESCRIPTION
**Pull request by tokou**

### CODE REVIEW

**Comment by tokou** [comment]
Could not run a test because of issues with the android SDK on my machine.

**Comment by tokou** [comment]
I was able to test it and everything seems to work the same way 👍 
screen shot 2017-03-29 at 00 22 29

**Comment by orrc** [comment]
Cool, thanks! I'll take a proper look this week.

**Comment by orrc** [comment]
Thanks, @tokou!

**Pull request merged**
